### ISSUE TITLE
feat: add Colemak-DH ANSI/Orth Keyboard Layout

### ISSUE THREAD

**Issue by mlouielu** [chewing/libchewing#413]
WIP: I'm working on adding Colemak-DH ANSI/Orth keyboard layout.

Init test works, but need to resolve #412, and add unit test?

**Comment by kanru** [comment]
Unit test in https://github.com/chewing/libchewing/blob/master/test/test-bopomofo.c or https://github.com/chewing/libchewing/blob/master/test/test-keyboard.c would be good, but it might fail with Rust tests because the rust rewrite use a different mapping at https://github.com/chewing/libchewing/blob/master/src/editor/keymap.rs and https://github.com/chewing/libchewing/blob/master/capi/chewing-internal/src/bopomofo.rs#L29

I'm rewriting the key mapping logic in branch rust/line-editor so if you add unit test feel free to not touch rust part and comment the test out.

**Comment by kanru** [comment]
Did you push the change? The CI should show which test failed.

**Comment by mlouielu** [comment]
Done with #414
