### ISSUE TITLE
libchewing 0.8.3 cmake build failure

### ISSUE THREAD

**Issue by chenrui333** [chewing/libchewing#573]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  CMake Error at build/data/cmake_install.cmake:48 (file):
    file INSTALL cannot find
    "/tmp/libchewing-20240526-8184-ure9ze/libchewing-0.8.3/build/data/pinyin.tab":
    No such file or directory.
  Call Stack (most recent call first):
    build/cmake_install.cmake:47 (include)
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/9245173161/job/25431336495?pr=172810
relates to Homebrew/homebrew-core#172810

**Comment by yan12125** [comment]
The issue is that when `-D BUILD_TESTING=OFF` is used, static data files (pinyin.tab, swkb.dat, symbols.dat) are not copied to the binary directory as the target `all_static_data` is not built by default.

https://github.com/chewing/libchewing/blob/630904be227f2074d8a758dcac9b9cb9f1cfcf74/data/CMakeLists.txt#L22-L26

https://github.com/chewing/libchewing/blob/630904be227f2074d8a758dcac9b9cb9f1cfcf74/tests/CMakeLists.txt#L60

Maybe the custom target `all_static_data` should use [the `ALL` option](https://cmake.org/cmake/help/latest/command/add_custom_target.html).

**Comment by chenrui333** [comment]
thanks @kanru @yan12125!
